export const players = [
  {
    firstName: 'Іван',
    lastName: 'Ємець',
    tshirtNumber: 1,
    position: 'ГК',
    team: '2013',
  },
  {
    firstName: 'Роман',
    lastName: 'Бруніч',
    tshirtNumber: 13,
    position: 'ЦЗ',
    team: '2013',
  },
  {
    firstName: 'Артем',
    lastName: 'Дерюгін',
    tshirtNumber: 26,
    position: 'ЦЗ',
    team: '2013',
  },
  {
    firstName: 'Марк',
    lastName: 'Подарін',
    tshirtNumber: 30,
    position: 'ЦПЗ',
    team: '2013',
  },
  {
    firstName: 'Дмитро',
    lastName: 'Лукянчук',
    tshirtNumber: 12,
    position: 'ЦПЗ',
    team: '2013',
  },
  {
    firstName: 'Олександр',
    lastName: 'Стоколос',
    tshirtNumber: 10,
    position: 'ППЗ',
    team: '2013',
  },
  {
    firstName: 'Ілля',
    lastName: 'Брагарь',
    tshirtNumber: 5,
    position: 'ППЗ',
    team: '2013',
  },
  {
    firstName: 'Максим',
    lastName: 'Ковальчук',
    tshirtNumber: 7,
    position: 'ЛПЗ',
    team: '2013',
  },
  {
    firstName: 'Андрій',
    lastName: 'Караджа',
    tshirtNumber: 11,
    position: 'ЦНП',
    team: '2013',
  },
  {
    firstName: 'Олексій',
    lastName: 'Полубняк',
    tshirtNumber: 1,
    position: 'ГК',
    team: '2014',
  },
  {
    firstName: 'Данііл',
    lastName: 'Демченко',
    tshirtNumber: 23,
    position: 'ЛЗ',
    team: '2014',
  },
  {
    firstName: 'Ілля ',
    lastName: 'Брагарь',
    tshirtNumber: 5,
    position: 'ПЗ',
    team: '2014',
  },
  {
    firstName: 'Святослав',
    lastName: 'Людвиченко',
    tshirtNumber: 16,
    position: 'ЦПЗ',
    team: '2014',
  },
  {
    firstName: 'Єгор',
    lastName: 'Чапалов',
    tshirtNumber: 2,
    position: 'ПНП',
    team: '2014',
  },
  {
    firstName: 'Олексій',
    lastName: 'Радулов',
    tshirtNumber: 26,
    position: 'ЛНП',
    team: '2014',
  },
  {
    firstName: 'Олег',
    lastName: 'Шкадовський',
    tshirtNumber: 7,
    position: 'ЦНП',
    team: '2014',
  },
  {
    firstName: 'Петро',
    lastName: 'Цуканов',
    tshirtNumber: 10,
    position: 'ЦПЗ',
    team: '2015',
  },
  {
    firstName: 'Олександр',
    lastName: 'Степанов',
    tshirtNumber: 10,
    position: 'ЦНП',
    team: '2015',
  },
  {
    firstName: 'Ігор',
    lastName: 'Загороднюк',
    tshirtNumber: 7,
    position: 'ЦНП',
    team: '2015',
  },
  {
    firstName: 'Герман',
    lastName: 'Колесник',
    tshirtNumber: 10,
    position: 'ЦНП',
    team: '2015',
  },
  {
    firstName: 'Олег',
    lastName: 'Шкадовський',
    tshirtNumber: 7,
    position: 'ЦНП',
    team: '2015',
  },
  {
    firstName: 'Дмитро',
    lastName: 'БIЛОУС',
    tshirtNumber: 19,
    position: 'ПЗ',
    team: '2015',
  },
  {
    firstName: 'Ілля',
    lastName: 'Мiкейчук',
    tshirtNumber: 5,
    position: 'ЛЗ',
    team: '2015',
  },
  {
    firstName: 'Чернявський',
    lastName: 'Чернявський',
    tshirtNumber: 5,
    position: 'ЦНП',
    team: '2015',
  },
  {
    firstName: 'Ілля',
    lastName: 'Потужний',
    tshirtNumber: 17,
    position: 'ЦПЗ',
    team: '2015',
  },
];
